// DO NOT CHANGE THIS FILE. This is an auto-generated list.
module.exports = {
  Cc: require('./category/Cc.js'),
  Zs: require('./category/Zs.js'),
  Po: require('./category/Po.js'),
  Sc: require('./category/Sc.js'),
  Ps: require('./category/Ps.js'),
  Pe: require('./category/Pe.js'),
  Sm: require('./category/Sm.js'),
  Pd: require('./category/Pd.js'),
  Nd: require('./category/Nd.js'),
  Lu: require('./category/Lu.js'),
  Sk: require('./category/Sk.js'),
  Pc: require('./category/Pc.js'),
  Ll: require('./category/Ll.js'),
  So: require('./category/So.js'),
  Lo: require('./category/Lo.js'),
  Pi: require('./category/Pi.js'),
  Cf: require('./category/Cf.js'),
  No: require('./category/No.js'),
  Pf: require('./category/Pf.js'),
  Lt: require('./category/Lt.js'),
  Lm: require('./category/Lm.js'),
  Mn: require('./category/Mn.js'),
  Me: require('./category/Me.js'),
  Mc: require('./category/Mc.js'),
  Nl: require('./category/Nl.js'),
  Zl: require('./category/Zl.js'),
  Zp: require('./category/Zp.js'),
  Cs: require('./category/Cs.js'),
  Co: require('./category/Co.js'),
};