// DO NOT CHANGE THIS FILE. This is an auto-generated list.
module.exports = {
  Cc: require('./Cc.js'),
  Cf: require('./Cf.js'),
  Co: require('./Co.js'),
  Cs: require('./Cs.js'),
  Ll: require('./Ll.js'),
  Lm: require('./Lm.js'),
  Lo: require('./Lo.js'),
  Lt: require('./Lt.js'),
  Lu: require('./Lu.js'),
  Mc: require('./Mc.js'),
  Me: require('./Me.js'),
  Mn: require('./Mn.js'),
  Nd: require('./Nd.js'),
  Nl: require('./Nl.js'),
  No: require('./No.js'),
  Pc: require('./Pc.js'),
  Pd: require('./Pd.js'),
  Pe: require('./Pe.js'),
  Pf: require('./Pf.js'),
  Pi: require('./Pi.js'),
  Po: require('./Po.js'),
  Ps: require('./Ps.js'),
  Sc: require('./Sc.js'),
  Sk: require('./Sk.js'),
  Sm: require('./Sm.js'),
  So: require('./So.js'),
  Zl: require('./Zl.js'),
  Zp: require('./Zp.js'),
  Zs: require('./Zs.js'),
};